// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ImageCreate = {
  title?: string | null
  category: string
  url: string
}

export type ImagePublic = {
  title?: string | null
  category: string
  url: string
  id: string
}

export type ImageUpdate = {
  title?: string | null
  category: string
  url: string
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type EndpointApiV1ImagesPostData = {
  requestBody: ImageCreate
}

export type EndpointApiV1ImagesPostResponse = unknown

export type EndpointApiV1ImagesGetData = {
  /**
   * Number of items per page
   */
  itemsPerPage?: number | null
  /**
   * Limit for unpaginated queries
   */
  limit?: number | null
  /**
   * Offset for unpaginated queries
   */
  offset?: number | null
  /**
   * Page number
   */
  page?: number | null
}

export type EndpointApiV1ImagesGetResponse = unknown

export type EndpointApiV1ImagesIdGetData = {
  id: string
}

export type EndpointApiV1ImagesIdGetResponse = unknown

export type EndpointApiV1ImagesIdPatchData = {
  id: string
  requestBody: ImageUpdate
}

export type EndpointApiV1ImagesIdPatchResponse = unknown

export type EndpointApiV1ImagesIdDeleteData = {
  id: string
}

export type EndpointApiV1ImagesIdDeleteResponse = unknown

export type UpsertMultipleImagesApiV1UpsertMultiImagesPostData = {
  requestBody: Array<ImageCreate>
}

export type UpsertMultipleImagesApiV1UpsertMultiImagesPostResponse =
  Array<ImagePublic> | null

export type HealthCheckApiV1UtilsHealthCheckGetResponse = boolean
