// This file is auto-generated by @hey-api/openapi-ts

export type Body_get_multi_images_api_v1_get_multi_images_post = {
  filter?: {
    [key: string]: string
  } | null
  sort_columns?: Array<string> | null
  sort_orders?: Array<string> | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ImageCreate = {
  title?: string | null
  category: string
  url: string
  width: number
  height: number
  captured_time: string
}

export type ImagePublic = {
  title?: string | null
  category: string
  url: string
  width: number
  height: number
  captured_time: string
  id: string
}

export type ImageUpdate = {
  title?: string | null
  category: string
  url: string
  width: number
  height: number
  captured_time: string
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type EndpointApiV1ImagesPostData = {
  requestBody: ImageCreate
}

export type EndpointApiV1ImagesPostResponse = unknown

export type EndpointApiV1ImagesIdGetData = {
  id: string
}

export type EndpointApiV1ImagesIdGetResponse = unknown

export type EndpointApiV1ImagesIdPatchData = {
  id: string
  requestBody: ImageUpdate
}

export type EndpointApiV1ImagesIdPatchResponse = unknown

export type EndpointApiV1ImagesIdDeleteData = {
  id: string
}

export type EndpointApiV1ImagesIdDeleteResponse = unknown

export type UpsertMultipleImagesApiV1UpsertMultiImagesPostData = {
  requestBody: Array<ImageCreate>
}

export type UpsertMultipleImagesApiV1UpsertMultiImagesPostResponse =
  Array<ImagePublic> | null

export type GetMultiImagesApiV1GetMultiImagesPostData = {
  limit?: number | null
  offset?: number
  requestBody?: Body_get_multi_images_api_v1_get_multi_images_post
}

export type GetMultiImagesApiV1GetMultiImagesPostResponse =
  Array<ImagePublic> | null

export type HealthCheckApiV1UtilsHealthCheckGetResponse = boolean

export type GetContainerSasApiV1UtilsContainerSasTokenGetResponse = string
